### ISSUE TITLE
nquiry Regarding Project Replication and Error Resolution

### ISSUE THREAD

**Issue by YutingWuTia** [wiseodd/lapeft-bayesopt#1]
An error popped up when I attempted to replicate it. 

<img width="789" alt="image" src="https://github.com/wiseodd/lapeft-bayesopt/assets/98287574/847e97bb-f1f4-4a03-806c-3c54e2d41656">

I'm wondering if the issue is due to a version difference in a certain package? Would you please provide me any advice about the error? Or maybe you prefer to share your requirement.txt so i can check for myself?

**Comment by wiseodd** [comment]
Could you please check if this commit fixes your issue? 
https://github.com/wiseodd/lapeft-bayesopt/commit/6c8740f30fe7fdcf85ce95c1e14928a34b776d4c

PS. make sure also that you installed `laplace-torch` and `asdl` in the given order,  as in the README.md:
```
pip install git+https://github.com/aleximmer/Laplace.git@mc-subset2
pip install git+https://github.com/wiseodd/asdl.git@dev
```
